import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {database,rpcFor,owner,other} from '../scripts/local-db.mjs';
import {httpServer} from '../scripts/http-server.mjs';
import {createHandler} from '../supabase/functions/calendar-api/handler.js';
let db,server,base;const logs=[],captures=[],allLogs=[];
const movies=()=>Array.from({length:24},(_,i)=>({day:i+1,title:'Movie '+(i+1)}));
async function clock(value){await db.exec(`create or replace function public.calendar_now() returns timestamptz language sql volatile set search_path='' as $$ select '${value}'::timestamptz; $$;`);}
async function request(path='',method='GET',data,identity='owner',key,extra={}){
 const headers={...(identity?{Authorization:'Bearer '+identity}:{}),...(key?{'X-Calendar-Token':key}:{}),...(data!==undefined?{'Content-Type':'application/json'}:{}),...extra};
 const response=await fetch(base+path,{method,headers,...(data!==undefined?{body:typeof data==='string'?data:JSON.stringify(data)}:{})});
 const text=await response.text();let json;try{json=JSON.parse(text);}catch{json={};}
 const result={status:response.status,headers:response.headers,json};
 if(captures.length<8)captures.push({method,path:base+path,requestHeaders:Object.fromEntries(Object.entries(headers).map(([k,v])=>[k,/authorization|token/i.test(k)?'[redacted]':v])),requestBody:data,responseStatus:result.status,responseHeaders:{'content-type':response.headers.get('content-type'),'x-request-id':response.headers.get('x-request-id')},responseBody:{...json,...(json.shareToken?{shareToken:'[redacted]'}:{})}});
 return result;
}
async function create(){const r=await request('','POST',{name:'Test calendar',year:2026,movies:movies()});assert.equal(r.status,201,JSON.stringify(r.json));return r.json;}
before(async()=>{db=await database();const handler=createHandler({rpc:rpcFor(db),user:async jwt=>jwt==='owner'?owner:jwt==='other'?other:null,origins:['https://calendar.test'],log:e=>{logs.push(e);allLogs.push(e);}});server=httpServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/functions/v1/calendar-api/calendars`;});
beforeEach(async()=>{await db.exec('truncate public.calendar_movies,public.calendars,public.calendar_limits;');await clock('2026-11-30T23:59:59Z');logs.length=0;});
after(async()=>{await mkdir('evidence',{recursive:true});await writeFile('evidence/local-http-capture.json',JSON.stringify({capturedAt:new Date().toISOString(),scope:'Actual local HTTP calls through production handler and SQL on PGlite. Identity verification is a test stub, not real Supabase Auth.',captures},null,2));await writeFile('evidence/local-log-correlation.json',JSON.stringify({scope:'Local integration-test server logs; same request IDs as the capture',logs:allLogs.filter(e=>captures.some(c=>c.responseHeaders['x-request-id']===e.requestId))},null,2));await new Promise(r=>server.close(r));await db.close();});
test('CRUD: create, read across independent requests, update and cascade delete',async()=>{const c=await create();let r=await request('/'+c.id,'GET',undefined,null,c.shareToken);assert.equal(r.status,200);assert.equal(r.json.movies.length,24);let next=movies();next[0].title='Klaus';r=await request('/'+c.id,'PATCH',{version:1,movies:next},null,c.shareToken);assert.equal(r.status,200);assert.equal(r.json.version,2);r=await request('/'+c.id);assert.equal(r.json.movies[0].title,'Klaus');r=await request('/'+c.id,'DELETE');assert.equal(r.status,200);assert.equal((await request('/'+c.id)).status,404);assert.equal((await db.query('select count(*)::int as n from public.calendar_movies')).rows[0].n,0);});
test('owner identity required for create and list',async()=>{assert.equal((await request('','POST',{name:'X',year:2026,movies:movies()},null)).status,401);assert.equal((await request('','GET',undefined,null)).status,401);});
test('unrelated account and missing or guessed link cannot read',async()=>{const c=await create();for(const who of ['other',null])assert.equal((await request('/'+c.id,'GET',undefined,who)).status,404);assert.equal((await request('/'+c.id,'GET',undefined,null,'0'.repeat(64))).status,404);});
test('forged or expired session is rejected before owner actions',async()=>{assert.equal((await request('','GET',undefined,'forged')).status,401);});
test('early lock blocks guest writes but allows owner writes',async()=>{const c=await create();let r=await request('/'+c.id+'/sharing','PATCH',{locked:true,version:1});assert.equal(r.status,200);r=await request('/'+c.id,'PATCH',{movies:movies(),version:2},null,c.shareToken);assert.equal(r.status,403);r=await request('/'+c.id,'PATCH',{movies:movies(),version:2});assert.equal(r.status,200);});
test('guest cannot lock, rotate or delete even with a valid link',async()=>{const c=await create();for(const [path,method,data] of [['/sharing','PATCH',{locked:true,version:1}],['/share-link','POST',{version:1}],['','DELETE',undefined]])assert.equal((await request('/'+c.id+path,method,data,null,c.shareToken)).status,403);});
test('December 1 boundary blocks owners and guests and cannot be unlocked',async()=>{const c=await create();await clock('2026-12-01T00:00:00Z');for(const who of ['owner',null])assert.equal((await request('/'+c.id,'PATCH',{movies:movies(),version:1},who,c.shareToken)).status,403);assert.equal((await request('/'+c.id+'/sharing','PATCH',{version:1,locked:false})).status,403);});
test('old calendar stays closed the following January',async()=>{const c=await create();await clock('2027-01-01T00:00:00Z');const r=await request('/'+c.id);assert.equal(r.json.closed,true);assert.equal(r.json.movies.filter(m=>m.title).length,24);assert.equal((await request('/'+c.id,'PATCH',{version:1,movies:movies()})).status,403);});
test('future titles withheld from locked guests and December viewers',async()=>{const c=await create();await request('/'+c.id+'/sharing','PATCH',{locked:true,version:1});let r=await request('/'+c.id,'GET',undefined,null,c.shareToken);assert.ok(r.json.movies.every(m=>m.title===''));await clock('2026-12-05T12:00:00Z');r=await request('/'+c.id);assert.equal(r.json.movies.filter(m=>m.title).length,5);});
test('rotating guest link revokes old link without exposing owner ID or hashes',async()=>{const c=await create();const r=await request('/'+c.id+'/share-link','POST',{version:1});assert.equal(r.status,200);assert.equal((await request('/'+c.id,'GET',undefined,null,c.shareToken)).status,404);const fresh=await request('/'+c.id,'GET',undefined,null,r.json.shareToken);assert.equal(fresh.status,200);for(const key of ['owner_id','share_hash','shareToken'])assert.equal(fresh.json[key],undefined);});
test('invalid movie lists rejected and transaction preserves previous data',async()=>{const c=await create();for(const change of [m=>m.slice(1),m=>{m[0].title='';return m;},m=>{m[0].title='x'.repeat(121);return m;},m=>{m[0].day=25;return m;},m=>{m[0].day=2;return m;},m=>{m[0].title=123;return m;}]){assert.equal((await request('/'+c.id,'PATCH',{version:1,movies:change(movies())})).status,400);}const r=await request('/'+c.id);assert.equal(r.json.version,1);assert.equal(r.json.movies[0].title,'Movie 1');});
test('invalid creation rolls back its calendar row',async()=>{assert.equal((await request('','POST',{name:'X',year:2026,movies:[]})).status,400);assert.equal((await request()).json.calendars.length,0);});
test('rejects owner spoofing and unexpected fields',async()=>{assert.equal((await request('','POST',{name:'X',year:2026,movies:movies(),owner_id:other})).status,400);});
test('simultaneous saves with one version have exactly one winner',async()=>{const c=await create();const r=await Promise.all([request('/'+c.id,'PATCH',{version:1,movies:movies()}),request('/'+c.id,'PATCH',{version:1,movies:movies()})]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);});
test('handles malformed JSON, huge body, wrong content type and unknown routes',async()=>{assert.equal((await request('','POST','{')).status,400);assert.equal((await request('','POST','x'.repeat(17000))).status,413);assert.equal((await request('','POST','{}','owner',undefined,{'Content-Type':'text/plain'})).status,415);assert.equal((await request('/not-an-id')).status,404);});
test('persistent quota returns 429 and Retry-After',async()=>{await db.query("insert into public.calendar_limits values($1,date_trunc('minute',clock_timestamp()),90)",['owner:'+owner]);const r=await request();assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'60');});
test('CORS permits configured website and rejects unexpected origin',async()=>{let r=await request('','OPTIONS',undefined,null,undefined,{Origin:'https://calendar.test'});assert.equal(r.status,204);assert.equal(r.headers.get('access-control-allow-origin'),'https://calendar.test');r=await request('','GET',undefined,'owner',undefined,{Origin:'https://evil.test'});assert.equal(r.status,403);assert.equal(r.headers.get('access-control-allow-origin'),null);});
test('safe error response and metadata-only correlated logs',async()=>{const c=await create();await request('/'+c.id,'GET',undefined,null,c.shareToken);assert.ok(logs.every(e=>Object.keys(e).sort().join(',')==='action,method,requestId,status'));assert.ok(!JSON.stringify(logs).includes(c.shareToken));const h=createHandler({rpc:async()=>({error:{message:'secret password',code:'XX000'}}),user:async()=>owner,origins:[],log:()=>{}});const r=await h(new Request(base));assert.equal(r.status,500);assert.ok(!(await r.text()).includes('secret password'));});
test('anon and authenticated cannot bypass API through tables or privileged functions',async()=>{for(const role of ['anon','authenticated']){await db.exec('set role '+role);try{await assert.rejects(db.query('select * from public.calendars'),/permission denied/);await assert.rejects(db.query("select public.calendar_api('list',$1,null,null,'{}')",[owner]),/permission denied/);}finally{await db.exec('reset role');}}});
test('saved PostgreSQL data survives closing and reopening the database',async()=>{const dir=await mkdtemp(join(tmpdir(),'calendar-persistence-'));let disk;try{disk=await database(dir);await disk.query('insert into public.calendars(owner_id,name,year,share_hash) values($1,$2,$3,$4)',[owner,'Survives restart',2027,'a'.repeat(64)]);await disk.close();disk=await database(dir);const r=await disk.query('select name from public.calendars');assert.equal(r.rows[0].name,'Survives restart');await disk.close();disk=null;}finally{if(disk)await disk.close();await rm(dir,{recursive:true,force:true});}});

 test('hosted gateway route keeps authorization and rejects unrelated paths',async()=>{
 const h=createHandler({rpc:rpcFor(db),user:async()=>null,origins:[],log:()=>{}});
 const unauth=await h(new Request('https://edge.test/calendar-api/calendars'));
 assert.equal(unauth.status,401);
 const wrong=await h(new Request('https://edge.test/other/calendars'));
 assert.equal(wrong.status,404);
 });
