<script setup lang="ts">
import {ref,computed,watch,onMounted,onUnmounted} from 'vue';
import Calendar from './components/Calendar.vue';
import MovieEditor from './components/MovieEditor.vue';
import OwnerLogin from './components/OwnerLogin.vue';
import {movies as defaults,type Movie} from './movies';
import {api,auth,configured,localTest,ApiError,type CalendarData,type Summary} from './backend';
const currentYear=new Date().getUTCFullYear();
const draftName=ref('Our Christmas movie nights'),draftYear=ref(new Date().getUTCMonth()===11?currentYear+1:currentYear),draftMovies=ref(defaults.map(m=>({...m})));
const active=ref<CalendarData|null>(null),items=ref<Summary[]>([]),guest=ref<string>(),shareLink=ref('');
const signedIn=ref(false),loginVisible=ref(false),busy=ref(false),loading=ref(true),editing=ref(false),ready=ref(false);
const message=ref(''),error=ref(''),conflict=ref(false),saveError=ref(''),deletePrompt=ref(false),rotatePrompt=ref(false);
const selectedId=ref<string|null>(null),openDay=ref<number|null>(null),opened=ref<number[]>([]),now=ref(Date.now());
let offset=0,timer:number,sequence=0,subscription:{unsubscribe:()=>void}|undefined;
const year=computed(()=>active.value?.year??draftYear.value),movies=computed(()=>active.value?.movies??draftMovies.value);
const closed=computed(()=>!!active.value&&(active.value.closed||now.value>=Date.UTC(year.value,11,1)));
const canEdit=computed(()=>active.value?active.value.canEdit&&!closed.value:!selectedId.value);
const available=computed(()=>{const d=new Date(now.value);return d.getUTCFullYear()>year.value?24:d.getUTCFullYear()<year.value||d.getUTCMonth()<11?0:Math.min(24,d.getUTCDate());});
const today=computed(()=>new Date(now.value).getUTCMonth()===11&&new Date(now.value).getUTCFullYear()===year.value?new Date(now.value).getUTCDate():null);
const historyKey=computed(()=>`shared-advent:${active.value?.id??'draft'}:${year.value}:opened`);
watch(historyKey,()=>{openDay.value=null;try{const parsed=JSON.parse(localStorage.getItem(historyKey.value)??'[]');opened.value=Array.isArray(parsed)?[...new Set(parsed.filter(d=>Number.isInteger(d)&&d>=1&&d<=24))]:[];}catch{opened.value=[];}},{immediate:true});
watch(closed,value=>{if(value&&editing.value){editing.value=false;message.value='December has arrived. Movie editing is closed for everyone.';}});
function toggleDoor(day:number){if(day>available.value)return;openDay.value=openDay.value===day?null:day;if(!opened.value.includes(day))opened.value=[...opened.value,day];try{localStorage.setItem(historyKey.value,JSON.stringify(opened.value));}catch{message.value='This browser could not remember your opened doors.';}}
function explain(e:unknown){conflict.value=e instanceof ApiError&&e.status===409;error.value=e instanceof Error?e.message:'Something went wrong. Please retry.';if(e instanceof ApiError&&e.requestId)error.value+=` Reference: ${e.requestId}`;}
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;sequence++;loading.value=false;error.value='';message.value='';conflict.value=false;try{await fn();}catch(e){explain(e);}finally{busy.value=false;}}
function apply(c:CalendarData){active.value=c;offset=Date.parse(c.serverNow)-Date.now();now.value=Date.now()+offset;}
async function list(){items.value=signedIn.value?(await api<{calendars:Summary[]}>()).calendars:[];}
async function load(quiet=false){const id=selectedId.value;if(!id)return;const seq=++sequence;if(!quiet)loading.value=true;try{const c=await api<CalendarData>(`/${id}`,'GET',undefined,guest.value);if(seq===sequence&&(!quiet||!editing.value))apply(c);}catch(e){if(seq===sequence){if(e instanceof ApiError&&[401,403,404].includes(e.status)){active.value=null;editing.value=false;}explain(e);}}finally{if(seq===sequence)loading.value=false;}}
async function fromLink(){if(busy.value)return;const p=new URLSearchParams(location.hash.slice(1));selectedId.value=p.get('calendar');guest.value=p.get('key')??undefined;active.value=null;shareLink.value='';editing.value=false;error.value='';deletePrompt.value=false;rotatePrompt.value=false;if(selectedId.value)await load();else{sequence++;loading.value=false;}}
function newCalendar(){if(busy.value)return;sequence++;selectedId.value=null;active.value=null;guest.value=undefined;shareLink.value='';editing.value=false;deletePrompt.value=false;rotatePrompt.value=false;error.value='';history.replaceState(null,'',location.pathname);}
function choose(id:string){if(!busy.value)location.hash=`calendar=${id}`;}
function sharingURL(id:string,key:string){return `${location.origin}${location.pathname}#${new URLSearchParams({calendar:id,key})}`;}
async function publish(){if(!signedIn.value){loginVisible.value=true;message.value='Your choices are ready. Verify your email, then save online.';return;}await run(async()=>{const c=await api<CalendarData>('','POST',{name:draftName.value,year:draftYear.value,movies:draftMovies.value});apply(c);selectedId.value=c.id;guest.value=undefined;shareLink.value=sharingURL(c.id,c.shareToken!);history.replaceState(null,'',`#calendar=${c.id}`);editing.value=false;message.value=localTest?'Calendar saved on the local test server. Copy your guest link below.':'Calendar saved online. Copy your guest link below.';await list();});}
async function saveMovies(next:Movie[]){saveError.value='';if(!active.value){draftMovies.value=next;editing.value=false;message.value='Draft movies updated. Save your calendar online when ready.';return;}await run(async()=>{try{apply(await api<CalendarData>(`/${active.value!.id}`,'PATCH',{movies:next,version:active.value!.version},guest.value));editing.value=false;message.value='Movies saved for everyone with access.';}catch(e){saveError.value=e instanceof Error?e.message:'Save failed.';throw e;}});}
async function lock(){await run(async()=>{apply(await api<CalendarData>(`/${active.value!.id}/sharing`,'PATCH',{locked:!active.value!.sharingLocked,version:active.value!.version}));message.value=active.value!.sharingLocked?'Shared editing locked. Only you can edit before December 1.':'Friends with the link can edit before December 1.';});}
async function rotate(){await run(async()=>{const c=await api<CalendarData>(`/${active.value!.id}/share-link`,'POST',{version:active.value!.version});apply(c);shareLink.value=sharingURL(c.id,c.shareToken!);rotatePrompt.value=false;message.value='New link created. The previous guest link no longer works.';});}
async function remove(){await run(async()=>{await api(`/${active.value!.id}`,'DELETE');sequence++;active.value=null;selectedId.value=null;guest.value=undefined;shareLink.value='';editing.value=false;deletePrompt.value=false;history.replaceState(null,'',location.pathname);message.value='Calendar deleted.';await list();});}
async function verified(){signedIn.value=true;loginVisible.value=false;await run(async()=>{await list();if(selectedId.value)await load();});message.value='Signed in. Save your draft or choose one of your calendars.';}
async function signOut(){await run(async()=>{if(localTest)sessionStorage.removeItem('calendar-test-owner');else{const r=await auth!.auth.signOut();if(r.error)throw r.error;}signedIn.value=false;items.value=[];sequence++;active.value=null;selectedId.value=null;shareLink.value='';guest.value=undefined;editing.value=false;history.replaceState(null,'',location.pathname);message.value='Signed out.';});}
async function copy(){try{await navigator.clipboard.writeText(shareLink.value);message.value='Link copied.';}catch{message.value='Select and copy the link manually.';}}
async function refresh(){if(editing.value&&!window.confirm('Discard this unsaved movie draft and load the latest version?'))return;editing.value=false;saveError.value='';error.value='';conflict.value=false;await load();}
function unload(event:BeforeUnloadEvent){if(editing.value){event.preventDefault();event.returnValue='';}}
onMounted(async()=>{try{if(localTest)signedIn.value=sessionStorage.getItem('calendar-test-owner')==='yes';else if(auth){signedIn.value=!!(await auth.auth.getSession()).data.session;subscription=auth.auth.onAuthStateChange((_event,s)=>{signedIn.value=!!s;}).data.subscription;}if(signedIn.value)await list();}catch(e){explain(e);}ready.value=true;await fromLink();window.addEventListener('hashchange',fromLink);window.addEventListener('beforeunload',unload);timer=window.setInterval(()=>{now.value=Date.now()+offset;if(selectedId.value&&active.value&&!editing.value&&!busy.value&&!loading.value&&document.visibilityState==='visible')void load(true);},30000);});
onUnmounted(()=>{clearInterval(timer);subscription?.unsubscribe();window.removeEventListener('hashchange',fromLink);window.removeEventListener('beforeunload',unload);});
</script>
<template><main>
<header class="masthead"><span class="brand"><span aria-hidden="true">✳</span> THE CHRISTMAS COLLECTION</span><a href="./report.html">Back-end report ↗</a></header>
<section class="intro"><p class="eyebrow">24 DOORS. 24 MOVIE NIGHTS.</p><h1>A very merry<br/><em>movie countdown.</em></h1><p class="intro-copy">Your favourite films. Your favourite people. One shared tradition.</p><p class="countdown">Editing closes December 1, {{year}} · 00:00 UTC</p></section>
<p v-if="localTest" class="notice" role="status">Local test mode · Real local PostgreSQL data, simulated owner identity. No email is sent. Public use requires Supabase setup.</p>
<p v-else-if="!configured" class="notice" role="status">Online saving is not connected yet. You can prepare a draft; see the setup guide to connect Supabase.</p>
<nav class="account-bar" aria-label="Calendar navigation"><button class="secondary-button" :disabled="busy||editing" @click="newCalendar">New calendar</button><button v-if="!signedIn" class="secondary-button" @click="loginVisible=!loginVisible">Owner sign in</button><button v-else class="secondary-button" :disabled="busy" @click="signOut">Sign out</button><span v-if="signedIn" class="small-note">{{localTest?'Local test owner':'Owner signed in'}}</span></nav>
<OwnerLogin v-if="loginVisible&&!signedIn" @verified="verified"/>
<section v-if="signedIn" class="saved-calendars"><h2>Your calendars</h2><p v-if="!items.length">No saved calendars yet.</p><div class="button-row"><button v-for="c in items" :key="c.id" class="secondary-button" :disabled="busy||editing" @click="choose(c.id)">{{c.name}} · {{c.year}}</button></div></section>
<p v-if="message" class="notice" role="status">{{message}}</p><div v-if="error" class="notice error" role="alert"><p>{{error}}</p><button v-if="selectedId" class="secondary-button" :disabled="busy" @click="refresh">{{conflict?'Load latest version':'Retry loading'}}</button></div>
<p v-if="loading||!ready" role="status">Loading your calendar…</p>
<section v-else-if="!selectedId||active" class="calendar-section" aria-label="Movie calendar">
<form v-if="!active" class="account-card" @submit.prevent="publish"><h2>Make a calendar to share</h2><p>Choose your movies first. Verify your email when you save and share.</p><div class="inline-form"><label>Calendar name<input v-model="draftName" required maxlength="80" :disabled="busy"/></label><label>December year<select v-model.number="draftYear" :disabled="busy"><option :value="currentYear">{{currentYear}}</option><option :value="currentYear+1">{{currentYear+1}}</option></select></label><button class="save-button" :disabled="busy||editing||!configured">{{busy?'Saving…':'Save & share calendar'}}</button></div><p class="small-note">Drafts stay in this page until saved. Finish movie edits before saving online.</p></form>
<div class="calendar-heading"><div><h2>{{active?.name??draftName}}</h2><p>{{active?(closed?'The movie list is set. Editing is closed for everyone.':active.sharingLocked?'Shared editing is locked.':'Friends with the link can help choose movies.'):'Your unsaved draft'}}</p></div><span class="access-badge">{{active?(active.isOwner?'Owner':'Guest'):'Draft'}}</span></div>
<div class="movie-settings"><p>{{canEdit?'Choose all 24 films before December 1.':'Open a new surprise on each December day.'}}</p><button v-if="canEdit&&!editing" class="secondary-button" :disabled="busy" @click="editing=true;saveError='';error=''">Choose movies</button><button v-if="active" class="secondary-button" :disabled="busy" @click="refresh">Refresh</button></div>
<MovieEditor v-if="editing&&canEdit" :movies="movies" :save-error="saveError" :busy="busy" :online="!!active" @save="saveMovies" @cancel="editing=false"/>
<section v-if="active?.isOwner" class="owner-controls" aria-label="Owner controls"><div class="button-row"><button v-if="!closed" class="secondary-button" :disabled="busy||editing" @click="lock">{{active.sharingLocked?'Allow friends to edit':'Lock shared editing'}}</button><button class="secondary-button" :disabled="busy||editing" @click="rotatePrompt=!rotatePrompt">Replace sharing link</button><button class="secondary-button" :disabled="busy" @click="deletePrompt=!deletePrompt">Delete calendar</button></div>
<p class="small-note">Only the owner can change sharing or delete. Deletion and link revocation remain available after the movies freeze.</p>
<div v-if="rotatePrompt" class="notice"><p>A replacement link stops the previous guest link from working. Continue?</p><button class="save-button" :disabled="busy" @click="rotate">Create replacement link</button> <button class="secondary-button" @click="rotatePrompt=false">Cancel</button></div>
<div v-if="deletePrompt" class="notice"><p>Permanently delete “{{active.name}}” and its movies? This cannot be undone.</p><button class="save-button" :disabled="busy" @click="remove">Yes, delete calendar</button> <button class="secondary-button" @click="deletePrompt=false">Keep calendar</button></div>
<div v-if="shareLink" class="share-box"><label>Guest sharing link<input :value="shareLink" readonly @focus="($event.target as HTMLInputElement).select()"/></label><button class="save-button" @click="copy">Copy guest link</button><p class="small-note">Copy it now. We store only its fingerprint. If you lose it, replace it. Anyone receiving this link can forward it.</p></div></section>
<Calendar :movies="movies" :available-day="available" :today="today" :open-day="openDay" :opened-days="opened" @toggle="toggleDoor"/>
<div class="calendar-foot"><span>{{opened.length}} of 24 doors opened on this browser</span><span>Good films. Warm blankets. Christmas together.</span></div>
</section><footer>✧ A little tradition. A lot of Christmas. · <a href="./report.html">Read the back-end report</a></footer>
</main></template>
